// flow-typed signature: 5760fd4f3a7ca58359b5b87cc3f08fda
// flow-typed version: <<STUB>>/@material-ui/docs_v^1.0.0-alpha.3/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/docs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/docs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/docs/index.es' {
  declare module.exports: any;
}

declare module '@material-ui/docs/MarkdownElement/index' {
  declare module.exports: any;
}

declare module '@material-ui/docs/MarkdownElement/MarkdownElement' {
  declare module.exports: any;
}

declare module '@material-ui/docs/MarkdownElement/prism' {
  declare module.exports: any;
}

declare module '@material-ui/docs/NoSSR/index' {
  declare module.exports: any;
}

declare module '@material-ui/docs/NoSSR/NoSSR' {
  declare module.exports: any;
}

declare module '@material-ui/docs/NProgressBar/index' {
  declare module.exports: any;
}

declare module '@material-ui/docs/NProgressBar/NProgressBar' {
  declare module.exports: any;
}

declare module '@material-ui/docs/svgIcons/GitHub' {
  declare module.exports: any;
}

declare module '@material-ui/docs/svgIcons/LightbublFull' {
  declare module.exports: any;
}

declare module '@material-ui/docs/svgIcons/Twitter' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/docs/index.es.js' {
  declare module.exports: $Exports<'@material-ui/docs/index.es'>;
}
declare module '@material-ui/docs/index' {
  declare module.exports: $Exports<'@material-ui/docs'>;
}
declare module '@material-ui/docs/index.js' {
  declare module.exports: $Exports<'@material-ui/docs'>;
}
declare module '@material-ui/docs/MarkdownElement/index.js' {
  declare module.exports: $Exports<'@material-ui/docs/MarkdownElement/index'>;
}
declare module '@material-ui/docs/MarkdownElement/MarkdownElement.js' {
  declare module.exports: $Exports<'@material-ui/docs/MarkdownElement/MarkdownElement'>;
}
declare module '@material-ui/docs/MarkdownElement/prism.js' {
  declare module.exports: $Exports<'@material-ui/docs/MarkdownElement/prism'>;
}
declare module '@material-ui/docs/NoSSR/index.js' {
  declare module.exports: $Exports<'@material-ui/docs/NoSSR/index'>;
}
declare module '@material-ui/docs/NoSSR/NoSSR.js' {
  declare module.exports: $Exports<'@material-ui/docs/NoSSR/NoSSR'>;
}
declare module '@material-ui/docs/NProgressBar/index.js' {
  declare module.exports: $Exports<'@material-ui/docs/NProgressBar/index'>;
}
declare module '@material-ui/docs/NProgressBar/NProgressBar.js' {
  declare module.exports: $Exports<'@material-ui/docs/NProgressBar/NProgressBar'>;
}
declare module '@material-ui/docs/svgIcons/GitHub.js' {
  declare module.exports: $Exports<'@material-ui/docs/svgIcons/GitHub'>;
}
declare module '@material-ui/docs/svgIcons/LightbublFull.js' {
  declare module.exports: $Exports<'@material-ui/docs/svgIcons/LightbublFull'>;
}
declare module '@material-ui/docs/svgIcons/Twitter.js' {
  declare module.exports: $Exports<'@material-ui/docs/svgIcons/Twitter'>;
}
